### PR TITLE
Fix `unknown options` in `tl_user`

### LINKED ISSUE #17: Unknown options in `tl_user`
All users in the demo have unknown options for:

- backendTheme
- news permissions
- event permissions

contao-demo-unknown-options

### PR DESCRIPTION
**Pull request by zoglo**
Fixes #17 

All users have been updated.

@aschempp are you gonna upstream or is the 5.x a different PR

### CODE REVIEW

**Comment by sascha-mueller** [comment]
@zoglo Thank you for your support. I'll have a look at it this weekend.

**Comment by aschempp** [comment]
5.3 is gonna be a new branch and 5.2 will be dropped as soon as 5.3 is released. We'll only manage the current versions.

**Comment by zoglo** [comment]
What I meant is if that should be a follow-up PR into the 5.3 branch or if it's gonna be merged from this one :)

**Comment by fritzmg** [comment]
I would assume that any database changes cannot be merged upstream, can they?

**Comment by sascha-mueller** [comment]
@fritzmg As far as I know, there is no way to do this except to copy it together manually.

**Pull request merged**
